ENV['RCT_USE_PREBUILT_RNCORE'] = '0'

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [__dirname]})'
], __dir__).strip

platform :ios, '15.1'
prepare_react_native_project!

$RNFirebaseAsStaticFramework = true
use_frameworks! :linkage => :static

pre_install do |installer|
  installer.pod_targets.each do |target|
    if target.respond_to?(:platform_name) && target.platform_name == :ios
      target.build_settings.each do |config_name, setting|
        setting['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
  end
end

target 'YoutubeApp' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
  end
end